import { defineConfig } from 'vite';
import { resolve } from 'path';

// Get base path from environment variable, default to /cubio/
const basePath = process.env.GITHUB_PAGES_BASE || '/cubio/';
console.log('Vite base path:', basePath);

export default defineConfig({
  base: basePath,
  server: {
    port: 3000,
    open: true
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
    rollupOptions: {
      output: {
        format: 'es',
        // Bundle everything into a single file to avoid IIFE format conflicts with cubing library
        inlineDynamicImports: true
      }
    },
    commonjsOptions: {
      transformMixedEsModules: true
    }
  },
  resolve: {
    alias: {
      'gan-web-bluetooth': resolve(__dirname, 'node_modules/gan-web-bluetooth/src/index.ts')
    }
  },
  optimizeDeps: {
    exclude: ['gan-web-bluetooth'],
    include: ['aes-js', 'rxjs'],
    esbuildOptions: {
      loader: {
        '.ts': 'ts'
      }
    }
  },
  ssr: {
    noExternal: ['gan-web-bluetooth']
  },
  worker: {
    // Force workers generated by cubing/search to stay as single-file ES modules.
    // The library triggers Rollup's classic-worker pipeline, which defaults to IIFE
    // and breaks when code-splitting is introduced. Keeping ES format and inlining
    // dynamic imports avoids the "Invalid value \"iife\"" error during build.
    format: 'es',
    rollupOptions: {
      output: {
        inlineDynamicImports: true
      }
    }
  }
});
